language: minimal
env:
- GHCVER=8.2
- GHCVER=8.4
- GHCVER=8.6
- GHCVER=head

script:
- export HLINT_ARGUMENTS=preprocessor test plugin
- curl -sSL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
